# -*- mode: python ; coding: utf-8 -*-
"""
智论助手 - PyInstaller 打包配置
生成单文件 exe，包含 Flask 后端 + 前端资源
"""

import sys
from pathlib import Path

block_cipher = None

# 项目根目录
PROJECT_ROOT = Path(SPECPATH).parent if hasattr(sys, '_MEIPASS') else Path(SPECPATH)

# ---------------------------------------------------------------------------
# 资源清单（v2.14 全量补齐）
#
# ⚠️ 这张表必须与 app.py / audit.py 的 **顶层 import** 保持一致。
#    漏掉任何一个 → exe 双击后 ImportError，且报错发生在 Flask 启动之前，
#    用户看到的是闪退，极难自查。
#
# 上次打包（9/11）就栽在这里：datacheck / table_check / grimmer /
# access_guard / paper_writer / defense_pack / security_guard /
# cross_platform / methods_registry / tone_guide 全部缺失。
# 新增模块时**必须**回来补一行，并在 docs/ARCHITECTURE.md 里同步登记。
# ---------------------------------------------------------------------------
datas = [
    # Flask 应用
    ('app.py', '.'),
    # 模板和静态文件
    ('templates', 'templates'),
    # 示例数据
    ('examples', 'examples'),
    # 依赖模块（agents 包）
    ('agents', 'agents'),

    # —— 论文解析与核查 ——
    ('extract_paper.py', '.'),
    ('audit.py', '.'),
    ('audit_chat.py', '.'),
    ('table_check.py', '.'),        # v2.12 文本形态表格交叉核查
    ('grimmer.py', '.'),            # v2.13 GRIMMER 检验（唯一真源）

    # —— 数据体检（产品入口）——
    ('datacheck.py', '.'),
    ('defense_pack.py', '.'),       # v2.10 ⑧答辩准备包

    # —— 方法注册表 / 知识图谱（总线 seam）——
    ('methods_registry.py', '.'),
    ('methods_graph.py', '.'),

    # —— 写作副驾流水线 ——
    ('pipeline.py', '.'),
    ('paper_writer.py', '.'),
    ('paper_polisher.py', '.'),

    # —— LLM 层（无 Key 时静默降级）——
    ('llm_cache.py', '.'),
    ('llm_enhance.py', '.'),
    ('llm_audit.py', '.'),
    ('llm_review.py', '.'),
    ('multimodal_agent.py', '.'),   # v2.9 ④多模态图表核查

    # —— 导出 ——
    ('export_docx.py', '.'),

    # —— 基础设施（★ 新增模块最容易漏的四兄弟）——
    ('env_loader.py', '.'),         # .env 加载器
    ('tone_guide.py', '.'),         # 文案口吻红线（被 llm_enhance / agents.prompts 依赖）
    ('security_guard.py', '.'),     # v1.7 限流与防御
    ('cross_platform.py', '.'),     # v2.8 跨端适配（默认关闭）
    ('access_guard.py', '.'),       # v2.13 访问门禁（默认关闭）

    # —— v2.14 可插拔方法市场（插件市场全套，缺一不可）——
    ('plugin_registry.py', '.'),    # 插件扫描 / 沙箱调度 / 结果合理性校验
    ('plugin_worker.py', '.'),      # 子进程沙箱入口（python -m plugin_worker）
    ('plugins', 'plugins'),         # 插件本体目录（run_tost.py 等，用户可自行往里加）

    # —— 其余被 import 链引用的业务模块（保险起见全部随包）——
    ('simulate.py', '.'),           # ⑥模拟数据生成器

    # —— 前端静态资源（PWA：sw.js / manifest / 图标 / 离线页）——
    ('static', 'static'),
]

# 收集隐藏导入（Flask 依赖）
hiddenimports = [
    'flask',
    'werkzeug',
    'jinja2',
    'markupsafe',
    'click',
    'itsdangerous',
    'requests',          # agents 各平台 HTTP 兜底
    'openai',            # 通用适配器（OpenAI 兼容多平台）
    'docx',              # python-docx：论文 .docx 读取 / Word 导出
    'pypdf',             # 论文 .pdf 读取（万方/知网 AES 加密自动解）
    'openpyxl',          # pandas 读 .xlsx
    'numpy',
    'scipy',
    'scipy.stats',
    'scipy.special',
    'scipy.linalg',
    'scipy.optimize',
    'scipy.interpolate',
    'scipy.integrate',
    'scipy.signal',
    'scipy.ndimage',
    'scipy.spatial',
    'scipy.cluster',
    'scipy.fft',
    'scipy.io',
    'pandas',
    'pandas.core',
    'pandas.core.frame',
    'pandas.core.series',
    'pandas.core.indexes',
    'pandas.core.dtypes',
    'pandas.core.reshape',
    'pandas.core.tools',
    'pandas.core.util',
    'pandas.io',
    'pandas.io.formats',
    'pandas.io.json',
    'pandas.io.parsers',
    'pandas.io.stata',
    'pandas.io.excel',
    'pandas.io.sql',
    'pandas.io.pytables',
    'pandas.io.clipboard',
    'pandas.io.common',
    'pandas.io.date_converters',
    'pandas.io.feather_format',
    'pandas.io.gbq',
    'pandas.io.html',
    'pandas.io.orc',
    'pandas.io.packers',
    'pandas.io.parquet',
    'pandas.io.pickle',
    'pandas.io.sas',
    'pandas.io.spss',
    'pandas.io.string',
    'pandas.io.xml',
    'pandas._libs',
    'pandas._libs.tslibs',
    'pandas._libs.tslibs.np_datetime',
    'pandas._libs.tslibs.nattype',
    'pandas._libs.tslibs.timezones',
    'pandas._libs.tslibs.conversion',
    'pandas._libs.tslibs.fields',
    'pandas._libs.tslibs.offsets',
    'pandas._libs.tslibs.parsing',
    'pandas._libs.tslibs.period',
    'pandas._libs.tslibs.strptime',
    'pandas._libs.tslibs.timedeltas',
    'pandas._libs.tslibs.timestamps',
    'pandas._libs.tslibs.tzconversion',
    'pandas._libs.tslibs.vectorized',
    'pandas.compat',
    'pandas.compat.numpy',
    'pandas.core.algorithms',
    'pandas.core.array_algos',
    'pandas.core.arrays',
    'pandas.core.arrays.arrow',
    'pandas.core.arrays.boolean',
    'pandas.core.arrays.categorical',
    'pandas.core.arrays.datetimelike',
    'pandas.core.arrays.datetimes',
    'pandas.core.arrays.floating',
    'pandas.core.arrays.integer',
    'pandas.core.arrays.interval',
    'pandas.core.arrays.masked',
    'pandas.core.arrays.numpy_',
    'pandas.core.arrays.period',
    'pandas.core.arrays.sparse',
    'pandas.core.arrays.string_',
    'pandas.core.arrays.string_arrow',
    'pandas.core.arrays.timedeltas',
    'pandas.core.base',
    'pandas.core.common',
    'pandas.core.computation',
    'pandas.core.config_init',
    'pandas.core.construction',
    'pandas.core.flags',
    'pandas.core.frame',
    'pandas.core.generic',
    'pandas.core.indexers',
    'pandas.core.indexers.objects',
    'pandas.core.indexes',
    'pandas.core.indexes.accessors',
    'pandas.core.indexes.api',
    'pandas.core.indexes.base',
    'pandas.core.indexes.category',
    'pandas.core.indexes.datetimelike',
    'pandas.core.indexes.datetimes',
    'pandas.core.indexes.extension',
    'pandas.core.indexes.frozen',
    'pandas.core.indexes.interval',
    'pandas.core.indexes.multi',
    'pandas.core.indexes.period',
    'pandas.core.indexes.range',
    'pandas.core.indexes.timedeltas',
    'pandas.core.internals',
    'pandas.core.internals.blocks',
    'pandas.core.internals.concat',
    'pandas.core.internals.construction',
    'pandas.core.internals.managers',
    'pandas.core.internals.ops',
    'pandas.core.missing',
    'pandas.core.nanops',
    'pandas.core.ops',
    'pandas.core.ops.array_ops',
    'pandas.core.ops.common',
    'pandas.core.ops.dispatch',
    'pandas.core.ops.docstrings',
    'pandas.core.ops.invalid',
    'pandas.core.ops.mask_ops',
    'pandas.core.ops.methods',
    'pandas.core.ops.missing',
    'pandas.core.resample',
    'pandas.core.reshape',
    'pandas.core.reshape.api',
    'pandas.core.reshape.concat',
    'pandas.core.reshape.melt',
    'pandas.core.reshape.merge',
    'pandas.core.reshape.pivot',
    'pandas.core.reshape.reshape',
    'pandas.core.reshape.tile',
    'pandas.core.reshape.util',
    'pandas.core.roperator',
    'pandas.core.sample',
    'pandas.core.series',
    'pandas.core.shared_docs',
    'pandas.core.sorting',
    'pandas.core.strings',
    'pandas.core.strings.accessor',
    'pandas.core.strings.base',
    'pandas.core.strings.object_array',
    'pandas.core.tools',
    'pandas.core.tools.datetimes',
    'pandas.core.tools.numeric',
    'pandas.core.tools.timedeltas',
    'pandas.core.tools.times',
    'pandas.core.util',
    'pandas.core.util.hashing',
    'pandas.core.util.numba_',
    'pandas.core.window',
    'pandas.core.window.common',
    'pandas.core.window.doc',
    'pandas.core.window.ewm',
    'pandas.core.window.expanding',
    'pandas.core.window.numba_',
    'pandas.core.window.online',
    'pandas.core.window.rolling',
    'pandas.errors',
    'pandas.io',
    'pandas.io.api',
    'pandas.io.clipboards',
    'pandas.io.common',
    'pandas.io.date_converters',
    'pandas.io.excel',
    'pandas.io.excel._base',
    'pandas.io.excel._odfreader',
    'pandas.io.excel._odswriter',
    'pandas.io.excel._openpyxl',
    'pandas.io.excel._pyxlsb',
    'pandas.io.excel._util',
    'pandas.io.excel._xlrd',
    'pandas.io.excel._xlsxwriter',
    'pandas.io.feather_format',
    'pandas.io.formats',
    'pandas.io.formats.console',
    'pandas.io.formats.css',
    'pandas.io.formats.csvs',
    'pandas.io.formats.excel',
    'pandas.io.formats.format',
    'pandas.io.formats.html',
    'pandas.io.formats.info',
    'pandas.io.formats.latex',
    'pandas.io.formats.printing',
    'pandas.io.formats.string_',
    'pandas.io.formats.style',
    'pandas.io.formats.style_render',
    'pandas.io.formats.xml',
    'pandas.io.gbq',
    'pandas.io.html',
    'pandas.io.json',
    'pandas.io.json._json',
    'pandas.io.json._normalize',
    'pandas.io.json._table_schema',
    'pandas.io.orc',
    'pandas.io.packers',
    'pandas.io.parquet',
    'pandas.io.parsers',
    'pandas.io.parsers.arrow_parser_wrapper',
    'pandas.io.parsers.base_parser',
    'pandas.io.parsers.c_parser_wrapper',
    'pandas.io.parsers.python_parser',
    'pandas.io.parsers.readers',
    'pandas.io.pickle',
    'pandas.io.sas',
    'pandas.io.sas.sas7bdat',
    'pandas.io.sas.sas_reader',
    'pandas.io.sas.sas_xport',
    'pandas.io.spss',
    'pandas.io.sql',
    'pandas.io.stata',
    'pandas.io.xml',
    'pandas.plotting',
    'pandas.plotting._core',
    'pandas.plotting._matplotlib',
    'pandas.plotting._matplotlib.boxplot',
    'pandas.plotting._matplotlib.converter',
    'pandas.plotting._matplotlib.core',
    'pandas.plotting._matplotlib.groupby',
    'pandas.plotting._matplotlib.hist',
    'pandas.plotting._matplotlib.misc',
    'pandas.plotting._matplotlib.style',
    'pandas.plotting._matplotlib.timeseries',
    'pandas.plotting._matplotlib.tools',
    'pandas.testing',
    'pandas.tseries',
    'pandas.tseries.api',
    'pandas.tseries.frequencies',
    'pandas.tseries.offsets',
    'pandas.util',
    'pandas.util._decorators',
    'pandas.util._doctools',
    'pandas.util._exceptions',
    'pandas.util._print_versions',
    'pandas.util._tester',
    'pandas.util._validators',
    'pandas.util.testing',
    'dateutil',
    'dateutil.parser',
    'dateutil.relativedelta',
    'dateutil.tz',
    'dateutil.zoneinfo',
    'pytz',
    'six',
    'openpyxl',
    'openpyxl.cell',
    'openpyxl.chart',
    'openpyxl.chartsheet',
    'openpyxl.comments',
    'openpyxl.compat',
    'openpyxl.descriptors',
    'openpyxl.drawing',
    'openpyxl.formatting',
    'openpyxl.formula',
    'openpyxl.image',
    'openpyxl.packaging',
    'openpyxl.pivot',
    'openpyxl.reader',
    'openpyxl.styles',
    'openpyxl.utils',
    'openpyxl.utils.datetime',
    'openpyxl.utils.escape',
    'openpyxl.utils.formulas',
    'openpyxl.utils.units',
    'openpyxl.workbook',
    'openpyxl.worksheet',
    'openpyxl.writer',
    'openpyxl.xml',
    'docx',
    'docx.api',
    'docx.enum',
    'docx.exceptions',
    'docx.opc',
    'docx.parts',
    'docx.styles',
    'docx.table',
    'docx.text',
    'docx.shared',
    'docx.oxml',
    'docx.oxml.ns',
    'docx.oxml.parser',
    'docx.oxml.simpletypes',
    'docx.dml',
    'docx.image',
    'docx.parts.document',
    'docx.parts.hdrftr',
    'docx.parts.image',
    'docx.parts.numbering',
    'docx.parts.settings',
    'docx.parts.styles',
    'docx.parts.table',
    'docx.parts.text',
    'docx.section',
    'docx.shape',
    'docx.text.font',
    'docx.text.hyperlink',
    'docx.text.pagebreak',
    'docx.text.paragraph',
    'docx.text.parfmt',
    'docx.text.run',
    'docx.text.tabstops',
    'lxml',
    'lxml.etree',
    'lxml.html',
    'lxml.objectify',
    'lxml.builder',
    'lxml.cssselect',
    'lxml._elementpath',
    'lxml.includes',
    'lxml.isoschematron',
    'lxml.pyclasslookup',
    'lxml.usedoctest',
    'PIL',
    'PIL.Image',
    'PIL.ImageDraw',
    'PIL.ImageFont',
    'PIL.ImageFilter',
    'PIL.ImageOps',
    'PIL.ImagePath',
    'PIL.ImageTransform',
    'PIL.TiffImagePlugin',
    'PIL.PngImagePlugin',
    'PIL.JpegImagePlugin',
    'PIL.GifImagePlugin',
    'PIL.BmpImagePlugin',
    'PIL.WmfImagePlugin',
    'PIL.PpmImagePlugin',
    'PIL.PdfImagePlugin',
    'PIL.TgaImagePlugin',
    'PIL.IcoImagePlugin',
    'PIL.IcnsImagePlugin',
    'PIL.MpoImagePlugin',
    'PIL.MspImagePlugin',
    'PIL.PcxImagePlugin',
    'PIL.SgiImagePlugin',
    'PIL.XbmImagePlugin',
    'PIL.XpmImagePlugin',
    'PIL.DdsImagePlugin',
    'PIL.FtexImagePlugin',
    'PIL.FliImagePlugin',
    'PIL.FpxImagePlugin',
    'PIL.BlpImagePlugin',
    'PIL.PixarImagePlugin',
    'PIL.QoiImagePlugin',
    'PIL.McIdasImagePlugin',
    'PIL.ImImagePlugin',
    'PIL.GbrImagePlugin',
    'PIL.CurImagePlugin',
    'PIL.DcxImagePlugin',
    'PIL.EpsImagePlugin',
    'PIL.PsdImagePlugin',
    'PIL.SunImagePlugin',
    'PIL.WalImagePlugin',

    # —— agents 包（含全部 provider 子模块）——
    'agents',
    'agents.router',
    'agents.prompts',
    'agents.openai_compat',
    'agents.secrets_guard',
    'agents.siliconflow_agent',
    'agents.zhipu_agent',
    'agents.deepseek_agent',
    'agents.qwen_agent',
    'agents.maas_agent',
    'agents.kimi_agent',
    'agents.mimo_agent',

    # —— 项目自有模块：PyInstaller 的静态分析看不透跨模块 import 时兜一手 ——
    #     （datas 里已带源码；这里再列一次，双保险，代价只有几十 KB）
    'access_guard',
    'audit',
    'audit_chat',
    'cross_platform',
    'datacheck',
    'defense_pack',
    'env_loader',
    'export_docx',
    'extract_paper',
    'grimmer',
    'llm_audit',
    'llm_cache',
    'llm_enhance',
    'llm_review',
    'methods_graph',
    'methods_registry',
    'multimodal_agent',
    'paper_polisher',
    'paper_writer',
    'pipeline',
    'security_guard',
    'table_check',
    'tone_guide',

    # —— LLM 调用所依赖 ——
    'urllib.request',
    'http.client',
    'ssl',
    'json',
    'csv',
    'zipfile',
    'base64',
    'hashlib',
    'hmac',

    # —— 可选解析后端：装了就用，没装则对应格式降级 ——
    'pdfplumber',
    'xlrd',
]

a = Analysis(
    ['desktop_launcher.py'],
    pathex=[],
    binaries=[],
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='智论助手',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='assets/icon.ico',
)
